spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://192.168.1.139:3306/tobsport
    username: andrew
    password: tobilko
server:
  address: 192.168.1.139
  port: 5000
